[package]
name = "exec_snoop"
version = "0.1.0"
authors = ["Ricardo Delfin <me@rdelfin.com>"]
edition = "2019"

[dependencies]
byteorder = "1.3.2"
chrono = "0.4.9"
ctrlc = "3.1.3"
failure = "0.1.5"
libc = "0.2.62"
systemstat = "0.1.4"

[dependencies.bcc]
features=["v0_5_0"]
version="0.0.12"
