[package]
name = "exec_snoop"
version = "0.1.0"
authors = ["Ricardo Delfin <me@rdelfin.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
byteorder = "1.3.2"
libc = "0.2.62"
ctrlc = "3.1.3"
chrono = "0.4.9"

[dependencies.bcc]
version="0.0.12"
features=["v0_5_0"]
